### ISSUE TITLE
Data recovery of PAOF needs to be supplemented

### ISSUE THREAD

**Issue by hshs1103** [addb-swstarlab/ParallelAOF#1]
@addb-swstarlab @mathcom @JuYeon28 

I reviewed the commit for each situation in which a system error could occur.

[ from https://github.com/addb-swstarlab/ParallelAOF/commit/959eb940378a7751b147a66631d2367c945d84df  to

https://github.com/addb-swstarlab/ParallelAOF/commit/8ecdb1c37ed22d86d09d8b8a0d6b36ca2ac5ce7c ]

Most of the data recovery situation is reflected, but there are some missing parts.

It is necessary to supplement the situation that operates after completion of the initial trigger.

*Please consider the situation where PAOF files and Temp PAOF files coexist after the initial work.

**Comment by addb-swstarlab** [comment]
@hshs1103 

We will design the data recovery process for the situation you mentioned and reflect it in the repository.

**Comment by addb-swstarlab** [comment]
Hello @hshs1103 

@JuYeon28  reflected your request.

[https://github.com/addb-swstarlab/ParallelAOF/commit/c27c088b32043c51f5eb507ffb612bd6d70375af]

**Comment by hshs1103** [comment]
@addb-swstarlab @JuYeon28 

After analyzing the code, it seems to have been reflected normally. Please close the issue.
