### ISSUE TITLE
PAOF need to be improved (remove AOF Rewrite Buffer)

### ISSUE THREAD

**Issue by addb-swstarlab** [addb-swstarlab/ParallelAOF#2]
@hshs1103 @mathcom @dkdl012 @JuYeon28 @Blue1993 

The currently released v1.1.0 PAOF uses AOF Rewrite Buffer. 

AOF Rewrite Buffer is the main reason for increased memory usage and poor data processing performance.

It is somewhat improved over existing techniques by utilizing data parallelism, but further improvement is needed.

**Comment by JuYeon28** [comment]
@addb-swstarlab 

To alleviate the AOF log file reconstruction overhead, we have completed the implementation of a technique for performing a rebuild without using an AOF Rewrite buffer.

**Comment by addb-swstarlab** [comment]
@JuYeon28 

I reviewed the committed code.
It seems that data recovery needs to be modified. I will register a new issue.
