### ISSUE TITLE
Data recovery modification is necessary due to the removal of the AOF Rewrite buffer

### ISSUE THREAD

**Issue by addb-swstarlab** [addb-swstarlab/ParallelAOF#3]
During PAOF operation, the AOF Rewrite buffer is not used, requiring modifications to the data recovery process.

*Currently, the recovery logic is unable to recover data for errors that occurred during the PAOF operation.

Please design a new data recovery process and modify it.

**Comment by hshs1103** [comment]
We will proceed after discussing the issue with the research team.

**Comment by hshs1103** [comment]
@addb-swstarlab 

The use of AOF Rewrite buffer has been removed from the logging version and all subsequent data recovery has been modified.
If you have any additional questions, please contact @Blue1993  and @JuYeon28 .

**Comment by addb-swstarlab** [comment]
we have confirmed what you said. This issue will be closed.
